packages:
  - name: myApp
    actions:
      - name: hello
        runtime: 'nodejs:default'
        web: true
        environment:
          DB_HOSTNAME: "${DB_HOSTNAME}"
      - name: newRow
        runtime: 'nodejs:default'
        web: true
        environment:
          DB_HOSTNAME: "${DB_HOSTNAME}"
      - name: triggered
        runtime: 'nodejs:default'
        web: true
        environment:
          DB_HOSTNAME: "${DB_HOSTNAME}"
