packages:
  - name: myApp
    actions:
      - name: hello
        runtime: 'nodejs:default'
        web: true
        environment:
          DATABASE_URL: "${FRONT_URL}"
      - name: newRow
        runtime: 'nodejs:default'
        web: true
        environment:
          FRONT_URL: "${FRONT_URL}"
      - name: triggered
        runtime: 'nodejs:default'
        web: true
        environment:
          FRONT_URL: "${FRONT_URL}"
