name: myslsapp
functions:
  - name: backend
    github:
      repo: Misfits09/do-sls
      branch: master
      deploy_on_push: true
    source_dir: ./functions
    envs:
      - key: DB_HOSTNAME
        value: "${maindb.PRIVATE_DOMAIN}"
        scope: RUN_TIME
    routes:
      - path: /api
services:
  - name: maindb
    github:
      repo: Misfits09/do-sls
      branch: master
      deploy_on_push: true
    source_dir: ./database
    dockerfile_path: ./database/Dockerfile
    internal_ports: [5432]
    envs:
      - key: TRIGGER_ENDPOINT
        value: "${backend.HOSTNAME/triggered}"
        scope: BUILD_TIME