name: myslsapp
functions:
  - name: backend
    github:
      repo: Misfits09/do-sls
      branch: master
      deploy_on_push: true
    source_dir: ./functions
    envs:
      - key: DB_URL
        value: "${maindb.DATABASE_URL}"
        scope: RUN_TIME
    routes:
      - path: /api
databases:
  - name: maindb
    engine: PG
    production: false